export const SOME_NAME = "SOME VALUE";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const CHANGE_STATE_PROP = "_CHANGE_STATE_PROP";
export const CREATE_MAP_POINT = "CREATE_MAP_POINT";
export const DELETE_MAP_POINT = "DELETE_MAP_POINT";
