export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const CHANGE_STATE_PROP = "_CHANGE_STATE_PROP";
export const CREATE_MAP_POINT = "CREATE_MAP_POINT";
export const DELETE_MAP_POINT = "DELETE_MAP_POINT";
export const CHANGE_GOOGLE_MAP_MARK_TEXT = "CHANGE_GOOGLE_MAP_MARK_TEXT";
export const INPUT_IN_FOCUS = "INPUT_IN_FOCUS";

